### ISSUE TITLE
Publish on Github Marketplace

### ISSUE THREAD

**Issue by shyamd** [Materials-Consortia/optimade-validator-action#10]
Do we want to publish this on the actions marketplace?

**Comment by CasperWA** [comment]
That is the intent. However, we need to accept some terms and conditions on behalf of Materials-Consortia, so I thought to bring this up at the meeting tomorrow and (hopefully) publish afterwards.
It was crucial to get this into a separate repository first though, to properly be able to show the work and contents of it, not having it mixed up with the Python tools, since it's indeed not Python dependent.

But please glance through [the GitHub Developer Agreement](https://help.github.com/en/github/site-policy/github-marketplace-developer-agreement) before tomorrow, so we can properly identify any possible issues and layout the general terms at the meeting. Already @ml-evs and I have or will go through it.

**Comment by CasperWA** [comment]
Voting comment: Agree

**Comment by CasperWA** [comment]
Voting comment: Disagree

**Comment by CasperWA** [comment]
Please vote with a thumbs up on each of the voting comments above! The vote will be closed on **Friday the 20.03.2020** or as soon as there is majority.

**Comment by CasperWA** [comment]
Tagging all members:
@adorsk @ajm143 @ankitkariryaa @blokhin @CasperWA @coreyoses @ctoher @davidwaroquiers @dsdavide @dwinston @fawzi @fekad @fraricci @giovannipizzi @gjc29 @gmrigna @gpetretto @hautierg @karstenwj @kxyyang @ltalirz @markus1978 @maxhutch @merkys @mkhorton @ml-evs @muhrin @nicolamarzari @nmounet @rartino @sauliusg @shyamd @tachyontraveler @tdarcher @tpurcell90 @waychal

**Comment by CasperWA** [comment]
The deadline has been long passed, and not a single of the (currently 6) votes disagree with Materials-Consortia accepting GitHub Developer Agreement for publishing this Action.
So I will shortly publish this Action in the name of the Materials-Consortia team.

**Comment by CasperWA** [comment]
This is hereby published on GitHub Marketplace. See the entry [here](https://github.com/marketplace/actions/optimade-validator).
